### ISSUE TITLE
Investigate interoperability issue with Bootstrap Template

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#118]
... as identified in the support forum: https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1344889#post1344889

**Comment by lat9** [comment]
The `tpl_modules_opc_shopping_cart.php` rendering will require a template-override version of that template file, due to the `bootstrap` template's table-row-based formatting of the order totals.

Find
```php
if (MODULE_ORDER_TOTAL_INSTALLED) {
    $row_class = ($last_row_class == 'rowEven') ? 'rowOdd' : 'rowEven';
//-bof-opc/bootstrap, added <table></table> since the order totals are displayed as table-rows.
?>     
        <tr class="<?php echo $row_class; ?>" id="cartOrderTotals">
            <td colspan="<?php echo (count($order->info['tax_groups']) > 1) ? 4 : 3; ?>" id="orderTotalDivs"><?php $order_total_modules->process (); $order_total_modules->output(); ?></td>
        </tr>
<?php
//-eof-opc/bootstrap
}
?>
```

and wrap the order_total_modules' output with a `<table></table>` pair:

```php
if (MODULE_ORDER_TOTAL_INSTALLED) {
    $row_class = ($last_row_class == 'rowEven') ? 'rowOdd' : 'rowEven';
//-bof-opc/bootstrap, added <table></table> since the order totals are displayed as table-rows.
?>     
        <tr class="<?php echo $row_class; ?>" id="cartOrderTotals">
            <td colspan="<?php echo (count($order->info['tax_groups']) > 1) ? 4 : 3; ?>" id="orderTotalDivs"><table width="100%"><?php $order_total_modules->process (); $order_total_modules->output(); ?></table></td>
        </tr>
<?php
//-eof-opc/bootstrap
}
?>
```
This will be **_documented_** in the OPC's readme.

**Comment by drbyte** [comment]
Can the `<table></table>` exist safely in both versions? thus preventing the need for an override?

**Comment by lat9** [comment]
Unfortunately, no.  The base, i.e. `template_default` and `responsive_classic` templates both use a nested `<div>` structure while `bootstrap` uses table-row (`<tr>`) elements.  The table-rows need a table to live in; the nested divs would need a table, table-row and table-column.

**Comment by drbyte** [comment]
In many ways the data for order-totals is indeed a data-table, particularly when it is presented as part of the list of items in the shopping-basket, since it starts with presenting a sum of the listed items, and then adds more data-items as additional subtotals to be included in a final total. 
Thus presenting as a table isn't "wrong".  
That doesn't mean it couldn't be changed to use div's.  Granted, bootstrap favors using a table when trying to present this sort of data, so changing to nested divs will be more complicated.
