### ISSUE TITLE
Some payment-methods or order-totals dependent on shipping-module selection

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#127]
See [this ](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1345382#post1345382)support-thread posting for additional information.

Essentially, might need to re-render the full `checkout_one` page on a change to shipping to fully emulate the 3-page checkout's flow.

**Comment by lankeeyankee** [comment]
Is it not possible to treat each area on the page as a separate block and do an XHR when a block is edited or a complete re-render/refresh if JS is disabled?
