### ISSUE TITLE
Correct shipping/billing address change handling 

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#132]
Related to #131.  If you
- change shipping address on page
- select 'cancel'
- change shipping address on page, again
- add/cancel/save buttons do not show

Most likely culprit is the AJAX handler not setting those "address-editable" flags.  I'm pretty sure that a similar issue is present for the billing address.

See [this ](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1345754#post1345754)Zen Cart posting for additional information.

**Comment by simon1066** [comment]
FYI, the billing address section does not exhibit this issue.

**Comment by lat9** [comment]
Thanks, @simon1066!
