### ISSUE TITLE
Option to show/change currency - Enhancement

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#149]
Recent posts in the forum addressed both Canadian sites selling to the US and US sites selling to Canada.

With the symbol for both USD and CAD being $, there seems to be confusion when customers checkout as they have no way of knowing if they are paying in "their" currency.

Apparently, even with the currencies side box turned on, customers from both sides were confused and bought in the wrong currency.

Perhaps a check to see if there is more than one currency, then something can be inserted in the shopping-cart block to remind the customer of the current currency and give the option to change the checkout currency.

If nothing else, perhaps a warning that there are more than one currency, it's currently set at %%%%,  and to ensure that the correct one is chosen.

**Comment by lat9** [comment]
For clients that have both a CA and US presence, I suggest that they modify the _**Symbol Left**_ values `Localization->Currencies/Canadian Dollar` and `US Dollar` to **CA$** and **US$**, respectively, to reduce that confusion.

**Comment by lat9** [comment]
> Good tip. Still hope to see a change button in the future. Hence the enhancement.

After review, this is a niche change and won't be incorporated in the base OPC distribution.
