### ISSUE TITLE
Disallow Guest Checkout for Gift Certificate Purchases?

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#150]
Due to the way that Gift Certificates/Vouchers work, _an actual customer account_ is required to actually spend a purchased GC.  That's because &mdash; unlike downloads, which are tied to an _order_ &mdash; a GC-balance is tied to a _customer_.  When the customer's a guest, there's no customer account available.

I'm thinking to disable the guest-checkout when a GC is in the cart, and would appreciate any/all comments.

**Comment by drbyte** [comment]
Agreed. Given that the current architecture has GC's tied to a customer record, there's no point purchasing without an account.  Simplest approach is to disable guest checkout when such a product is in the cart. 

I imagine other scenarios might require disabling guest checkout as well, such as purchasing a membership subscription where memberships are linked to a store account.

**Comment by lat9** [comment]
The "Guest Checkout" button is still shown on the `login` page when GCs are present in the cart.
