### ISSUE TITLE
v156 files not fully incorporated

### ISSUE THREAD

**Issue by mc12345678** [lat9/one_page_checkout#151]
With the revision of the downloads process by incorporating the ZC 1.5.6 versions of 
`includes/modules/pages/download/header_php.php`
and
`includes/modules/downloads.php`
installation of this plugin to use the current template (YOUR_TEMPLATE) is expected to be successful at handling downloads. However, if an alternate template is selected (including, for example, either of the default classic templates of ZC 1.5.5), downloads will be broken because of the differences in versions of ZC 1.5.6 and previous versions of the file `includes/templates/template_default/templates/tpl_modules_downloads.php`.

Also, while the downloads files have mostly been incorporated, the ajax.php file remains at the ZC 1.5.5 version which is different than the ZC 1.5.6 version.

**Comment by lat9** [comment]
Thanks for the update!  I see that

1. There's been a zc156 change to `includes/classes/observers/auto.downloads_via_redirect.php`, which I'll update for OPC.
2. The zc156 version of `includes/modules/pages/download/header_php.php` has not been updated to ensure that the `timeout` page redirect is performed via SSL; I'll submit a PR to the zencart repo for this.
3. I'll document that the switch to either of the Zen Cart default templates (assuming that the store hasn't "cloned" them for use) will not properly support downloads ... at least until the store's default template files have been updated to the zc156 level.
4. The `ajax.php` file is no longer distributed by OPC, so the last comment is a non-issue.

**Comment by lat9** [comment]
Zen Cart PR for item 2, above: https://github.com/zencart/zencart/pull/1787

**Comment by lat9** [comment]
Commit just push covers the first item; I'll get the readme updated for the third shortly.

**Comment by mc12345678** [comment]
But, by incorporating this plugin, which includes incorporating `includes/modules/pages/download/header_php.php', it disables base functionality of downloads for systems that are not yet on the unreleased for production 1.5.6 version of Zen Cart.  

Shouldn't this plugin incorporate the file 'includes/templates/template_default/templates/tpl_modules_downloads.php' from ZC 1.5.6 into the store's template_default to not break the store as has been suggested regarding installing some of the files into the template_default directory? As of right now the version provided in the YOUR_TEMPLATE directory is the same as provided in ZC 1.5.6.  Meaning, the existing/remnant template_default version of the file is useless and problematic because of this plugin. The "solution" being to document the issue in the instructions?  

Now, if the operation provided by the header_php.php file were otherwise incorporated through some validation that the download will be able to occur, that would be different.

**Comment by lat9** [comment]
I'll consider your request.
