### ISSUE TITLE
Salutation Ms. is not saved on creation of guest account

### ISSUE THREAD

**Issue by BramF33** [lat9/one_page_checkout#152]
Create a guest account and select Ms. When saved it is automatically put back as Mr.
so can the salutation issue be fixed in next release??
thx

**Comment by lat9** [comment]
The plugin's jQuery handling needed (since the `gender` selection is a radio-type input) to gather the value from the `checked` radio button.  It was previously returning the value of the first (i.e. 'm') input found.
