### ISSUE TITLE
Feature request: update order total when COD is selected

### ISSUE THREAD

**Issue by Zen4All** [lat9/one_page_checkout#162]
It would be nice if the order total could be updated automatically when the cod payment method is selected, and there is a cod fee defined in the ot_cod_fee module

**Comment by lat9** [comment]
Hmm, v2.0.5 now refreshes the order-total block, as changed for #148, when any payment-method change occurs.

Is that not working for you?

**Comment by Zen4All** [comment]
Never mind, I see it does indeed update. I need more coffee 😊
