### ISSUE TITLE
Detect Framework JS on Template Default Instead of Custom Template

### ISSUE THREAD

**Issue by Pan2020** [lat9/one_page_checkout#178]
I'm installed the 2.1.0 Beta-5 and this error showed up.
https://i.imgur.com/OsrRmGH.png

The One-Page Checkout plugin has been disabled. The file "/.../public_html/zc156/includes/templates/custom/jscript/jscript_framework.php" is required for the plugin's proper operation.

However, in ZC 1.5.6b, the same JS file can be also found at `/includes/templates/template_default/jscript`

Therefore, should it detected such JS on default template if there is none in custom folder?

**Comment by lat9** [comment]
Unfortunately, no.  You'll need to copy jscript_framework.php from the template_default's jscript sub-directory to your customer template's.

**Comment by lat9** [comment]
Actually, I've always thought that the template-specific jscript was problematic.  I'll update the installation/update instructions to identify that any `custom` template should have a modified (i.e. requiring the base `template_default` version of that file.
