### ISSUE TITLE
guest state/zip pre-fill issue

### ISSUE THREAD

**Issue by archelaus-cards** [lat9/one_page_checkout#185]
Sorry to bring this up again, but 2.1.0beta5 still pre-fills the guest's state and zip to those of the store. I really do think you need to fix this. I've never seen a commercial website that makes this sort of assumption about where its customers are ordering from, and if you've addressed the underlying shipping-module reason for doing it, as I believe you now have, there really isn't any reason to have the program continue to pre-fill these fields.

I've been able to get rid of the zip code pre-fill by changing line 868 of OnePageCheckout.php to 'postcode' => '', but getting rid of the state pre-fill seems to be more complicated. I thought I had it fixed after I first asked about it in the support thread, but later I realized that no, I really hadn't, I've fooled around with the beta version now, too, hoping that the edits that didn't work before might work now, but no luck.

Thank you for all your efforts on a plugin that fixes a lot of the things I find least satisfactory about Zen Cart!

**Comment by lat9** [comment]
No problems, that was on my list of things to do now that the shipping/payment choices' blocks aren't displayed until the guest has entered his/her billing address information.

Thanks for the reminder!
