### ISSUE TITLE
free-shipping bug

### ISSUE THREAD

**Issue by archelaus-cards** [lat9/one_page_checkout#190]
I regret to report a problem with OPC’s interaction with the ot-shipping module, in which checkout gives free shipping to international orders, even though ot-shipping is configured only to give it to domestic ones.

I did a clean installation of Zen Cart 1.5.6a to make sure the problem wasn’t located there. To keep things simple, I configured Zen Cart with only one Payment Module, namely “Check/Money Order,” and one Shipping Module, namely “Zone Rates” (with DC and the USA as the only defined zones). I configured ot-shipping as follows: “Allow Free Shipping: True,” “Free Shipping For Orders Over: $40.00,” and “Provide Free Shipping For Orders Made: national.” The template is “Classic Contemporary Green.” Testing showed everything working fine. Foreign orders over $40 had to pay the full shipping cost.

Then I installed OPC 2.1.0beta6. Apart from activating the plug-in and enabling guest checkout, all I did was remove “money order” from “Guest Checkout: Disallowed Payment Methods,” to avoid any conflict on that front. Testing confirms that checkout is giving free shipping to international orders over $40, despite the ot_shipping setting to the contrary.

**Comment by archelaus-cards** [comment]
This is probably closely related to what I reported before, so I'll add it here. If I have a domestic free-shipping situation, with more than $40 in the cart, but then click to edit the cart and reduce the amount below $40, checkout still shows free shipping. (I should add that I'm not working with a "clean" install anymore, so it's vaguely possible that this is the result of some change I've made, but I don't think that's at all likely. It seems much more probable that the plug-in is just failing to reevaluate free-shipping situations as they change.)

**Comment by lat9** [comment]
The symptoms you've identified are those associated with the **_shipping, same as billing_** not "keeping up".  I should have an update pushed later today.

**Comment by archelaus-cards** [comment]
Are you sure that's true of both of these situations? Just editing the cart to change the amount ordered shouldn't implicate the shipping=billing issue, should it?

**Comment by lat9** [comment]
Yes, since the 'temporary' shipping address is currently not keeping track of the shipping=billing, changing the amount ordered (which could kick in the free-shipping) can have an effect.

**Comment by archelaus-cards** [comment]
Well, that fixed the second problem! Checkout's no longer keeping domestic free shipping when I change from an amount that qualifies to an amount that doesn't qualify. But I'm sorry to say the original problem is still with us. Checkout continues to show free shipping when I change from a domestic shipping address to an international one (assuming the order is large enough to qualify for domestic free shipping in the first place). This is true whether I check out as a guest or as a returning customer.

**Comment by lat9** [comment]
If I haven't said it before ... I _really_, **really** appreciate the effort that you're providing in the 3rd-party testing!

I'll give that a look in the morning.

**Comment by archelaus-cards** [comment]
You're very welcome! I'm glad to do it.

And, of course, thank **you** for all the work you're putting in to get these things fixed!

**Comment by lat9** [comment]
Arggh!  It's the shipping-estimator on the shopping-cart page that's resetting the session-defined sendto address since `$_SESSION['cart_address_id']` isn't set during OPC's processing.

**Comment by lat9** [comment]
FWIW, I've opened [this](https://github.com/zencart/zencart/issues/2234) Zen Cart issue to identify the problem.

**Comment by archelaus-cards** [comment]
I'm sure you're right that there's a problem with the shipping estimator, but is it the same problem I'm having? My original issue did not involve returning to the shopping cart. It just involved changing the shipping address from domestic to international. But I don't know. As my father used to say, "It's too deep for me!"

**Comment by archelaus-cards** [comment]
Incidentally, I'm actually getting a slightly different behavior than the one you're reporting on the Zen Cart page, but that may be due to a fairly radical tweak I've made to the shipping estimator. In trying to replicate the behavior you're reporting, I went to guest checkout, typed in a US address for billing, and typed in a German address for shipping (with an amount too small to qualify for free shipping). Then I returned to the shopping cart. The shipping estimator was still showing the default "United States," but with the correct amount for shipping to Germany. If I tried to change the drop-down to "Canada" or "Rest of the world" (these are the only options as a result of my tweak), it would insist on reverting to "United States," while, again, keeping the correct German shipping cost, based on the shipping address I had entered in checkout. Finally, when I clicked on checkout, the German address was still there, unchanged.

What I understand you to be saying on the Zen Cart page is that the shipping estimator is quietly changing the shipping address entered in checkout, whereas what my tweaked shipping estimator is doing instead is telling you how much it's going to cost to ship your order to the shipping address you entered, even if you try to ask it to estimate how much it will cost to ship it somewhere else. And it will do so while pretending that the shipping destination is the U.S. Again, I'm pretty sure that at least part of the behavior I'm seeing is because I inflicted a certain amount of blunt-force trauma on the shipping-estimator code earlier, in an attempt (which seemed successful at the time) to get it to do what I wanted, so I wouldn't read too much into this.

**Comment by lat9** [comment]
It's not that the shipping address itself is being changed, it's that the order's `$_SESSION['sendto']` is being modified outside of the checkout process.  

OPC thinks (or thought) that the checkout processing was "owned" by the checkout processing, and has stashed some data in the session so that it "knows" that a guest is going through checkout with shipping!=billing and _assumes_ that the standard Zen Cart session values for the sendto and billto addresses have remained intact.

**Comment by archelaus-cards** [comment]
Okay, but just as a reminder, the domestic-billing-foreign-shipping-free-shipping problem I originally reported did _not_ occur in the clean version of Zen Cart that I installed specifically to test for it. It only began after I then added OPC. How is that consistent with the idea that this is a Zen Cart bug, not an OPC one? I'm not trying to be argumentative here, I'm just in over my head.

I mean, I get that you've found and reported a genuine Zen Cart bug that you've confirmed occurs with the original three-page-checkout, but isn't that a separate problem from the one I first reported, since the latter does _not_ occur with three-page-checkout?

**Comment by lat9** [comment]
Part of the underlying cause of the issue is that OPC's processing combines all three steps of the 'base' checkout processing and, thus, presumes that it's in control of the overall process.  

It's a subtle bug for the 3-page checkout, i.e. a customer's pre-chosen shipping address is changed outside of the checkout process, but OPC's base processing uses the `$_SESSION['sendto']` value to determine whether (and if so which) of the order's _temporary_ addresses are currently in use as the shipping address.

**Comment by archelaus-cards** [comment]
Okay, so if I understand correctly, the shipping estimator is somehow interfering in the process even if the customer does not leave checkout and return to the shopping cart? Because my original problem did not involve returning to the cart.

**Comment by lat9** [comment]
There were two underlying issues:

1. OPC was not properly managing the free-shipping processing.
2. When leaving OPC to make modifications to the cart and then re-entering the OPC processing, the shipping 'basis' got out-of-whack due to the shipping-estimator's change to the order's shipping address id.

**Comment by archelaus-cards** [comment]
I'm afraid I'm not seeing any result from this fix. I take it we still need to wait for the Zen Cart gurus to squash the bug in their code?

**Comment by lat9** [comment]
Could you give a scenario where the output is not what you expect?  I've gone through various combinations of free-shipping, address-change and cart-contents-changes and don't see anything amiss.

**Comment by archelaus-cards** [comment]
The scenario I laid out in my original post still goes wrong, i.e., if I put over $40 in the cart, and then go to checkout and choose a domestic billing address and a foreign shipping address, checkout will award free shipping despite ot_shipping being set to give it only to domestic orders over $40, not foreign ones of whatever size.

Oh, crap. The second problem I reported in this thread, which was fixed by your first set of edits, has reappeared after your second set! If I put more than $40 in the cart, give a domestic shipping/billing address, then go back to the shopping cart and reduce the amount to under $40, checkout is now giving it free shipping again!

**Comment by archelaus-cards** [comment]
Interesting. In the latter case, if I then change the shipping address to Germany, checkout recognizes that the order is no longer entitled to free shipping. Whether that is because it notices that it's foreign or that it's below $40, I couldn't say.

**Comment by archelaus-cards** [comment]
Okay, if I then go back to the shopping cart and increase the amount to over $40, checkout refuses to grant free shipping. So it must be because by this time it has figured out that this is a foreign order. Also, at this point it correctly does the "(Shipping to DE)" thing that it didn't do before.

**Comment by archelaus-cards** [comment]
It occurs to me that there have been a lot of edits to includes/classes/OnePageCheckout.php in particular since the beta5 version I downloaded. I would like to think that I've made them all without slipping up even once, but that isn't necessarily true. Would it make sense for you to upload your latest version of the file in case installing that magically solves my problems? If so, perhaps it would be a good idea to upload includes/classes/observers/class.checkout_one_observer.php and includes/classes/ajax/zcAjaxOnePageCheckout.php, as well, just to be on the safe side?

**Comment by lat9** [comment]
All of those changes were pushed yesterday for beta7.

**Comment by archelaus-cards** [comment]
I didn't realize there was anywhere I could download beta8, but now that I've reloaded the GitHub page for beta5 and changed the URL to beta8, I've got it. GitHub does a pretty good job of hiding it. I still can't find any actual link to it! The "code" page seems to be all "commits."

Anyway, I'm both pleased and sorry to report that my ongoing updates to those three files, made on the basis of your "commits," were all error-free, so that's one theory out the window!

**Comment by archelaus-cards** [comment]
I decided to another fresh install of Zen Cart and a fresh install of beta8. I can confirm that you do seem to have solved the problems I was reporting with my previous fresh install of Zen Cart and beta6. So, it looks like it's up to me to figure out what stupidities I have perpetrated myself that are preventing your fixes from working. Sigh. Wish me luck! Many thanks for the help. I appreciate it.

**Comment by lat9** [comment]
You can see the number of changes made since a specific release by first navigating to (for OPC) https://github.com/lat9/one_page_checkout and clicking the "Releases" tab.  Each release's header looks similar to:
![image](https://user-images.githubusercontent.com/2685585/55288676-f2762f00-5388-11e9-84b0-2ed95b58cc2c.png)
... and clicking on that _xx commits_ to master link will show you the changes made (and files effected) since the associated release.

Thanks for letting me know that the issues you've reported have been corrected in beta8!  There are still a couple of refinements to be made, so keep on testing!

**Comment by archelaus-cards** [comment]
Okay, thanks! I didn't notice the "releases" tab.

Happily, last night I managed to find and squash the bug I introduced that was preventing your fix from working!
