### ISSUE TITLE
another minor shipping-related bug

### ISSUE THREAD

**Issue by archelaus-cards** [lat9/one_page_checkout#191]
Using the same zone-shipping set-up as last time, I find that if I change the shipping address to a country different from the one in the billing address, the shopping cart in checkout doesn't quite keep up. While it gets the changed shipping rate correct (obviously the most important thing), it continues to show the original destination country. So, for example, when I enter an American billing address and a German shipping address, it switches from:

Shipping (Shipping to US): $1.50
to:
Shipping (Shipping to US): $7.00
instead of:
Shipping (Shipping to DE): $7.00

It appears that $shipping_method, which is defined to include $dest_country in the file includes/modules/shipping/zones.php in line 201, 215, or 229, is not getting redefined.

**Comment by lat9** [comment]
To save me some time reproducing the issue (although the **_shipping=billing_** paths are currently my focus), does this occur during guest- or account-checkout or both?  My best guess is that it's the temporary address handling which, right now, what I'm working through.

**Comment by archelaus-cards** [comment]
It happens with both. In guest, I unclicked shipping=billing, added the new, foreign address, and it happened. But it also happened when I logged in and chose a foreign shipping address from the drop-down menu of existing addresses.

**Comment by lat9** [comment]
Thanks, I'll add that verification to the shipping=billing updates!

**Comment by lat9** [comment]
I've tested these scenarios on the most recent changes I've made for #190 and those changes appear to have resolved this issue as well.

**Comment by archelaus-cards** [comment]
Sigh. I'm sorry to say that I'm not seeing the same result that you are. I suppose it could be due some weird side-effect of my own changes, but I don't see how. Do you happen to know where the Order Totals module throws the parentheses around $shipping_method (or whatever variable it has set equal to $shipping_method)? For my purposes the easiest fix would be to delete that section of code so that the output is just "Shipping: $7.00" instead of the rather silly "Shipping (Shipping to US): $7.00." The only problem is that I can't figure out where this happens.

**Comment by lat9** [comment]
Could you post the contents of the zone-based shipping module that you're using?  There's _easily_ another variable that's anticipated to be set that I've missed.

**Comment by archelaus-cards** [comment]
I'm using the "Zone Rates (zones)" shipping module that comes with Zen Cart. It is currently defined with Zone 1 as US, Zone 2 as CA (i.e., Canada, not California), and Zone 3 as 00 (everywhere else). Each zone has various shipping prices set by weight (for example, Zone 1 is "2.5:1.50,8:3.50,12:4.00,10000:5.00"), but it is the "Shipping (ot_shipping)" module under Order Total that is set to give free shipping for domestic orders over $40. So shipping price is set by weight in the Zone Rates (zones) shipping module but potentially overridden by the value of the order in the Shipping (ot_shipping) module. For added terminological confusion, two altogether separate zones are defined under Locations/Taxes. One is the USA, the other is DC, which is defined as part of the USA and has a sales tax rate assigned to it.
