### ISSUE TITLE
OPC and shipping estimator

### ISSUE THREAD

**Issue by archelaus-cards** [lat9/one_page_checkout#193]
Working with my clean install of ZC 1.5.6a and OPC 2.1.0beta8, I've found what looks like a lingering bug from our shipping-billing address saga. If I use guest checkout, enter a billing address, enter a different shipping address, and then return to the shopping cart, the shipping estimator defaults to the billing address, which seems a bit counter-intuitive  (using returning-customer checkout it defaults to the shipping address, which seems more sensible). But more importantly, although there are two choices in the shipping estimator's drop-down, they both display _in the drop-down itself_ as if they were the billing address, so the customer appears to have no meaningful choice. In actual fact, selecting the second one does then display the correct full shipping address on the screen, but the customer has no way of knowing that this will happen. The problem does not occur in returning-customer checkout.

**Comment by lat9** [comment]
I'm going to leave the OPC/shipping-estimator interoperability issue to the next OPC release.

**Comment by archelaus-cards** [comment]
Fair enough. Can't blame you for that!

Unfortunately, I have more weird behavior to report. The clean install is now doing something wrong in returning-customer checkout, as well. Something it was not doing half-an-hour ago, even though I have not changed any code or settings in the meantime.

So, initially, after I logged in, there were two addresses in my address book. I left the billing address as default, but typed in a third address for shipping and saved it, but _without_ clicking the "Save to Address Book" checkbox. Then I went to the shopping cart. The shipping estimator displayed the correct shipping address on screen, while the drop-down gave as choices the two addresses in the address book. Okay, that's what I think it was supposed to do. BUT, then, half-an-hour later, after a lot of logging in and out, as well as switching to guest checkout and back again, I started getting some weird results. So, I closed and reopened the browser, logged in again, and repeated the exact same procedure as the first time, only to have the shipping estimator put the default billing address on the screen instead of the shipping address! Since the desired shipping address isn't in the address book, it ceased to be available to the customer as a shipping-estimator option at all.

Two notes: First, the problem is restricted to the shipping estimator. When I return to checkout, the shipping address is still correct, as is the shipping cost and the shipping method. Second, I don't have a clean installation of ZC available right now without OPC installed on top of it, so I don't know how that would behave in the same situation.

**Comment by archelaus-cards** [comment]
For future reference, please note that I've just figured out that in guest checkout, the shipping-estimator drop-down is _not_ showing the default billing address twice, as I assumed; rather it is showing the _location of the store._ So, I was getting ", DC, United States," which I mistook for a weirdly truncated form of my home address, which I was using for testing. When I switched to a default billing address in California, the drop-down continued to be ", DC, United States."

**Comment by lat9** [comment]
There are a couple of `shipping_estimator`-related changes that are required for its interoperation with _OPC_:

1.  `/includes/modules/shipping_estimator.php` and, if present, any template-override version.  Find the **two** occurrences of

    `if ($_SESSION['customer_id']) {` 

    and change to 

    `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

2. `/includes/templates/template_default/templates/tpl_modules_shipping_estimator.php` and, if present, any template-override version. Find the **one** occurrence of

   `if ($_SESSION['customer_id']) {` 

   and change to 

   `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

**Comment by lat9** [comment]
For **zc156a**:

1.  `/includes/modules/shipping_estimator.php` and, if present, any template-override version.  Find the **two** occurrences of

    `if (!empty($_SESSION['customer_id'])) {` 

    and change to 

    `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

2. `/includes/templates/template_default/templates/tpl_modules_shipping_estimator.php` and, if present, any template-override version. Find the occurrence of

   `if (!empty($_SESSION['customer_id'])) {` 

   and change to 

   `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

    Then find the occurrence of

    `<?php if (empty($_SESSION['customer_id'])){ ?>`

    and change to

    `<?php if (!zen_is_logged_in() || zen_in_guest_checkout()) { ?>`

**Comment by lat9** [comment]
For **zc156b**:

1.  `/includes/modules/shipping_estimator.php` and, if present, any template-override version.  Find the **two** occurrences of

    `if (!empty($_SESSION['customer_id'])) {` 

    and change to 

    `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

2. `/includes/templates/template_default/templates/tpl_modules_shipping_estimator.php` and, if present, any template-override version. Find the occurrence of

   `if (zen_is_logged_in()) {` 

   and change to 

   `if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

    Then find the occurrence of

    `<?php if (!zen_is_logged_in()){ ?>`

    and change to

    `<?php if (!zen_is_logged_in() || zen_in_guest_checkout()) { ?>`

**Comment by lat9** [comment]
Arggh, that's quite the mess.  I'll update the upgrade documentation to point to this issue rather than regurgitating these changes there!
