### ISSUE TITLE
Payment methods missing

### ISSUE THREAD

**Issue by scottcwilson** [lat9/one_page_checkout#197]
Using 2.1.0-beta5 (2019-03-12).  Seems like sometimes the payment methods don't show up on the first page load.  A refresh seems to fix this.  Have  you seen this?

**Comment by lat9** [comment]
I think I saw that behavior with that older beta; I'm up to v2.1.0-beta9 and suggest that you retest using that closer-to-release beta version,

**Comment by scottcwilson** [comment]
Thanks will do!

www.thatsoftwareguy.com -  eCommerce websites with Zen Cart!

**Comment by scottcwilson** [comment]
Yep, looks like it's fixed.  Thank you!
