### ISSUE TITLE
Correct AJAX session-save issue

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#22]
Need to include an updated version of the `/ajax.php` script; see [this ](https://www.zen-cart.com/showthread.php?220887-AJAX-Session-variable-changes-not-saved)Zen Cart posting for additional details.

**Comment by drbyte** [comment]
NOTE: Probably good to update this from https://github.com/zencart/zencart/pull/1298 ... which would make it compatible with v155, v155a, v155b ... and, I'm guessing also with this mod's v154 support.
