### ISSUE TITLE
In-compatibility with Ship2Pay module

### ISSUE THREAD

**Issue by Zen4All** [lat9/one_page_checkout#222]
On some site I use the ship2pay module, to make a combination between shipping and payment methods. I found that sometimes the review orde button did not change as it should be, because the correct payments modules are not always loaded at the time of page load.
Tis can be very easily overcome by changing the below lines from
https://github.com/lat9/one_page_checkout/blob/1f2ee28fc2207529dd0f4c0105f1739ba0c4ca05/includes/modules/pages/checkout_one/header_php.php#L348-L361
to
```php
// -----
// Determine if there are any payment modules that are in the confirmation-required list.
//
// The generated list is used within the /includes/modules/pages/checkout_one/jscript_main.php module to determine what text to
// display for the order-submittal text/title.
//
$confirmation_required = explode(',', CHECKOUT_ONE_CONFIRMATION_REQUIRED);
$required_list = '"' . implode('", "', $confirmation_required) . '"';
```
This skips IMHO the whole needles check,  and making all the payment mods entered in the admin always available.

**Comment by lat9** [comment]
@Zen4All, thanks for the detailed analysis, explanation and suggested change.  I'll get this rolled into the next version of One-Page Checkout.

**Comment by Zen4All** [comment]
thx 👍

**Comment by lat9** [comment]
Very slight difference in the bits I just posted, to take care of a possible issue if there are _no_ payment methods requiring review.

**Comment by Zen4All** [comment]
Great, my code was just a quick workaround for my clients site.
Wil update to reflect your code.
