### ISSUE TITLE
Add configurable CSS/jQuery selector to identify template-specific total location

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#229]
Many of the now-popular templates have their own, unique formatting for a store's Order Totals block, provided by the template's `/templates/tpl_modules_order_totals.php`.  This has been problematic for _OPC_ since the order's current total (as present on the `checkout_one` order-entry page) gets passed to the order-confirmation step to make sure that the order, as calculated, has the same total that the customer last saw.

Adding a configuration setting (defaulting to the `responsive_classic` and `template_default` values) to allow a store to identify the CSS/jQuery selector that the storefront OPC's jQuery should use to "find" that value.  See [this](https://www.w3schools.com/cssref/css_selectors.asp) link on `w3schools` for help in determining the selector to be used.

**Comment by drbyte** [comment]
Would it work to check several "known" identifiers, in a fallback fashion? Might simplify or prevent the need for another configuration setting.

Or, if the value to check is contained within another element that you prescribe is "necessary" for OPC compatibility, then you could check for that.

**Comment by lat9** [comment]
There are just so many variations of the **_Order Totals_** block's formatting (specifically, the HTML layout thereof) that I'd prefer to 'push' this back to the store's configuration.  That, IMO, will provide the highest degree of interoperability for stores that are using those commercial templates.

One of the issues, too, is that no matter how much content I fold into the readme (both part of the distribution and on-line), very few people actually `RTFM`.

**Comment by haredo** [comment]
Love the RTFM quote !!!
