### ISSUE TITLE
Deletion of orders_products records 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/one_page_checkout#257]
If no changes have been made to the list of products in an order, it would be great if OPC could skip the step of deleting and re-adding the rows in the `orders_products` table.  The reason is, some mods (such as dropshipping) add data to those records which is not easily recreated.

**Comment by lat9** [comment]
I'm confused, @scottcwilson, _OPC_ has no play in deleting/adding those rows post-order.

**Comment by scottcwilson** [comment]
ARGH! I apologize - not enough coffee.  I mixed up EO and OPC.
