### ISSUE TITLE
Can't support zone name have single quotes

### ISSUE THREAD

**Issue by chenly** [lat9/one_page_checkout#261]
I will get a error msg if i add a zone name as Côte-d'Or in checkout page.

**Comment by lat9** [comment]
I'm not seeing that with _OPC_ v2.3.2 running on either zc156c or zc157-beta.

What version of OPC and Zen Cart are you using?

**Comment by chenly** [comment]
I running on OPC v2.3.2 + zc156c .  I have get a js error on chrome 80
in line 
var c2z = XXXXXXXXXXXX

**Comment by chenly** [comment]
![3 微信图片_20200615102858](https://user-images.githubusercontent.com/13716/84613014-d3fc4500-aef4-11ea-9dfc-3148f24fadd0.png)
![1 微信图片_20200615102841](https://user-images.githubusercontent.com/13716/84613019-d52d7200-aef4-11ea-9f67-d82f79b901a8.png)
![2 微信图片_20200615102852](https://user-images.githubusercontent.com/13716/84613023-d5c60880-aef4-11ea-96da-d820bb399247.png)
