### ISSUE TITLE
Form entries, use placeholder instead of extra span to identify required fields.

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#265]
... as identified in [this](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1371012#post1371012) Zen Cart support-thread post.

**Comment by lat9** [comment]
While I can't point to the spot where this change was made, the current implementation of OPC uses those placeholders for the required fields:
![image](https://user-images.githubusercontent.com/2685585/97304484-29951680-1832-11eb-8768-a34cdc32b314.png)

**Comment by simon1066** [comment]
Not sure if I'll be able to explain it properly but I guess what I'm getting at is, for Admin > Customer details > State - always as pulldown = false, the index.php?main_page=create_account page shows the asterisk inside the state field:
![Screenshot 2020-10-27 132643](https://user-images.githubusercontent.com/13421449/97307811-15641000-1858-11eb-8e9f-932f09c0957d.png)

whereas checking out as a guest on the index.php?main_page=checkout_one page shows the asterisk outside the state field:

![Screenshot 2020-10-27 132914](https://user-images.githubusercontent.com/13421449/97308159-74298980-1858-11eb-9b5f-c2bf1f275283.png)
