### ISSUE TITLE
null in state value.

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#270]
hi cindy,
i thought i would point this out.  not really sure how or if you want to do anything about it.  or if you already are aware.  if so, i apologize in advance.

i'm dealing with v158 install, and php 7.4.7

the creation of the address book table is so:
```
sql/install/mysql_zencart.sql:56:  entry_state varchar(32) default NULL,
```

in this repo, we do not add state for either the guest bill_to or send_to

https://github.com/lat9/one_page_checkout/blob/4f3d1275c907ccec24dd23bb56dfdc12aac3dbba/YOUR_ADMIN/includes/init_includes/init_checkout_one.php#L81-L88

if one, per chance, ends up editing that adddress, we get a fatal error:

--> PHP Fatal error: Uncaught TypeError: Argument 3 passed to zen_get_zone_name() must be of the type string, null given, called in /var/www/zcdev/admin/customers.php on line 710 and defined in /var/www/zcdev/includes/functions/functions_addresses.php:144

if the state was initialized as blank, this error would not occur.

not sure if it is worth fixing, or if we should potentially address it at the ZC repo, but i just thought i would point it out.

best.

**Comment by lat9** [comment]
Since the default value is NULL, I'll suggest that the correction be made in the base zencart repository.

**Comment by Zen4All** [comment]
probably related to https://github.com/zencart/zencart/issues/3917

**Comment by lat9** [comment]
Thanks for the pointer, @Zen4All.

**Comment by proseLA** [comment]
ok, i'm not sure the issues are related.  other than they are both part of the address book and involve zones.  maybe distant cousins....  i have always found ZCs implementation of zones problematic.

thanks both for looking.
