### ISSUE TITLE
DoubleSubmit Concerns

### ISSUE THREAD

**Issue by lindasdd** [lat9/one_page_checkout#274]
OPC utilizes the loading animation and 'doublesubmit/submitonce' function via the confirmation page.

The only problem with that (for me), is there is no such prevention on the actual order confirm/submit button.

The solution that worked for my exact needs was to do the following.

in includes\templates\YOUR_TEMPLATEE\templates\tpl_modules_opc_submit_block.php on line 22 I added the below pulled from the checkout_confirmation page:

<div id="checkoutOneConfirmationLoading" style="display: none;"><?php echo ((CHECKOUT_ONE_CONFIRMATION_INSTRUCTIONS == '') ? '' : (CHECKOUT_ONE_CONFIRMATION_INSTRUCTIONS . '<br /><br />')) . zen_image ($template->get_template_dir (CHECKOUT_ONE_CONFIRMATION_LOADING, DIR_WS_TEMPLATE, $current_page_base ,'images') . '/' . CHECKOUT_ONE_CONFIRMATION_LOADING, CHECKOUT_ONE_CONFIRMATION_LOADING_ALT); ?></div>

I also gave the button an id of 'opc-order-confirm-submit' (so that I could display/hide the button)

Then in includes\modules\pages\checkout_one\jquery.checkout_one.js I utilized the jQuery that is watching ajax start and stop:

jQuery(document).ajaxStart(function () {
        jQuery('*').css('cursor', 'wait');
        jQuery('#checkoutOneConfirmationLoading').show();
        jQuery('#opc-order-confirm-submit').hide();
    });

    jQuery(document).ajaxStop(function () {
        jQuery('*').css('cursor', '');
        jQuery('#checkoutOneConfirmationLoading').hide();
        jQuery('#opc-order-confirm-submit').show();
    });

**Comment by lat9** [comment]
@lindasdd, I chose to correct the issue somewhat differently.  See the changes submitted above to `/includes/modules/pages/checkout_one/jquery.checkout_one.js`.
