### ISSUE TITLE
create_account.css box-sizing omission

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#278]
Apologies if all this is known.  I am writing in my information for all style.

When combining a width or height call with a padding or margin call in CSS, the resulting box can often wind up larger than that intended.  A CSS Validator will report something like "Beware of broken box size."

On the first line of create_account.css, you can add border-box:box-sizing; resulting in:

`#opc-ca-left, #opc-ca-right {box-sizing:border-box;downloadwidth: 50%; float: left; padding: 10px; }`

This way the box maintains the wanted 50%.  If not added, a 1500px screen would have the width equal 760px versus 750.  Any border or other item with "thickness" will increase the true width/height.

A minimal factor in using this is that it is not supported in IE6 and IE7.  They are pre-XP versions of the browser and not supported.

This is often seen in Zen Cart when two boxes having 50% widths are put side by side or float:left/float:right.  Padding on either (without the box-sizing) will make them move to above and below versus side-by-side.

Found in the process of validating all 1.5.7a CSS for 1.5.8 in responsive_classic.

**Comment by lat9** [comment]
Thanks, @dbltoe, it turns out that the `create_account.css` file is redundant.  Those `opc-ca-left` and `opc-ca-right` elements don't exist and the styling for the buttons is 'built into' the `responsive_classic` template.

It'll be removed for v2.3.6.
