### ISSUE TITLE
JS alert when no shipping options are available

### ISSUE THREAD

**Issue by drbyte** [lat9/one_page_checkout#285]
When all the active/enabled shipping modules evaluate to "disabled" or "no quotes returned", the template doesn't output the usual DOM handles, so OPC can't find the IDs it's trying to attach to, thus throwing a JS alert.

Exposed, but not caused, [by this report in the ZipShip module support thread](https://www.zen-cart.com/showthread.php?221303-ZipShip-Support-Thread&p=1375734#post1375734).

Screenshots from responsive_classic:
<img width="447" alt="Screen Shot 2020-12-15 at 4 16 39 PM" src="https://user-images.githubusercontent.com/404472/102273959-255fae00-3ef1-11eb-97d0-142e0dd0b920.png">
<img width="306" alt="Screen Shot 2020-12-15 at 4 10 35 PM" src="https://user-images.githubusercontent.com/404472/102273974-2a246200-3ef1-11eb-99df-8e2ee31b6d89.png">
<img width="493" alt="Screen Shot 2020-12-15 at 4 10 29 PM" src="https://user-images.githubusercontent.com/404472/102273990-2db7e900-3ef1-11eb-83a6-d0df5cf8448f.png">

**Comment by lat9** [comment]
Noting that the same unwanted behavior exists when there are no payment methods available for the billing address.
