### ISSUE TITLE
Ambiguous coupon_id on register

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#295]
Sorry, the client deleted debugs.
When offering a discount coupon to New Customers (coupon_id 6 ) they were getting a warning that the coupon_id was ambiguous.
Changing line 349 of includes/modules/pages/create_account/header_php_create_account_register.php to be "WHERE **c.**coupon_id =$coupon_id" stopped the ambiguous warning.
Haven't had new registers but, the query works with the change.

**Comment by lat9** [comment]
I'll also take this opportunity to update that script to include zc157c-related changes.
