### ISSUE TITLE
Drop support for Zen Cart versions prior to 1.5.7a

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#304]
https://github.com/lat9/one_page_checkout/blob/b054ad79a7295d24393849c903ab1bd36d0f2b7f/includes/modules/pages/checkout_one/jscript_main.php#L7-L81

as documented here: 
https://www.crockford.com/javascript/script.html

"...In HTML, it is better to leave it out. The browser knows what to do."

also on the same page with regards to `<!--//-->`:

"...Do not use the  hack with scripts. It was intended to prevent scripts from showing up as text on the first generation browsers Netscape 1 and Mosaic. It has not been necessary for many years.  is supposed to signal an HTML comment. Comments should be ignored, not compiled and executed. Also, HTML comments are not to include --, so a script that decrements has an HTML error."

this hack has always confused me.  (no longer!)

with regards to who is douglas crawford, from his about page:
https://www.crockford.com/about.html

"...2001-2002. State Software, Inc. Founder, CTO.

State developed an application framework for highly-interactive web applications. I was one of the two principal architects. I developed the client technology. I met with investors and customers. I conducted training sessions. I led the technical team. I published articles. I filed a patent. **I discovered JSON.**

The State system was built around highly scalable session server that could support single and multiuser applications and mashups with a convenient programming model. **It anticipated Ajax.**"

so, i am curious why we continue with such things?

**Comment by lat9** [comment]
Lack of time?

**Comment by lat9** [comment]
See also #313; it required zc157+ for inclusion.

**Comment by lat9** [comment]
Besides removing the `zc155f` and `zc156` sub-directories from the distribution:
1. Use `foreach` instead of `while/MoveNext` when handling query returns from the $db.
2. Use `[]` instead of `array()`.
3. Use exactly-equal-to where appropriate.
