### ISSUE TITLE
One page checkout 2.3.11 not enabled

### ISSUE THREAD

**Issue by Theeba** [lat9/one_page_checkout#311]
Hi,

I have used zencart 1.5.6c version website and have installed "One page checkout 2.3.11" modules.

After uploaded the modules files in server not able to enable this module in admin.

And it shows below error message. we don't have the missing "jscript_framework.php" file from module folder.

So kindly review it and let us know the solutions for this ASAP!!.

**The One-Page Checkout plugin has been disabled. The file "/home/flowersx/public_html/includes/templates/yourstore/jscript/jscript_framework.php" is required for the plugin's proper operation.**

**Comment by lat9** [comment]
Does nobody ever read the readme?  On the first page, it clearly states:

> The plugin's design utilizes standard Zen Cart HTML/CSS layout when rendering its new pages, so the look-and-feel of your store gets "inherited". Some templates make drastic modifications to that layout — removing those standard HTML/CSS selectors — which causes this plugin's newly-added pages to display improperly. The following templates are known to be incompatible with the One-Page Checkout plugin:
> 
> * Tableau (numinix)
> * YourStore (themeforest)
> 

The message is (I thought) self-explanatory.  That template doesn't include a required Zen Cart file that's needed for the OPC to "do its thing".

**Comment by Theeba** [comment]
Hi,

Yes, in my website using the "YourStore " theme. Is any solution to rectify the problem to enable the 
"One page checkout 2.3.11" modules.

**Comment by lat9** [comment]
There is not.  As mentioned in the readme, One-Page Checkout is not supported when that template is in use.
