### ISSUE TITLE
Enable integration with `square_webPay` payment method.

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#317]
cindy,
i am having a problem with competing event listeners.  on some sites, the OPC click function gets registered first.  on other sites the square_webPay gets registered first.  when the square_webPay gets registered first, there is a successful transaction.  when OPC is first, it does not.  nor do some of the submitForm functions of OPC get run.

my dev box always loads the square_webPay first.  why other stores get OPC loaded first i have no been able to determine.

no one that is using square_webPay has complained about the OPC functions not running.

i'm not sure if the one of ajax calls is resetting the square form.

any thoughts?

if i were able to reproduce the loading of the event listeners, then perhaps i could solve it.  but i am not able to do that.

thanks.

**Comment by lat9** [comment]
@proseLA, if you've got a 'live' dev box (oxymoron?) let me know via direct email.  I'd need FTP access to the site so that I could try to "coerce" OPC to be loaded first.

**Comment by proseLA** [comment]
hi, i do not really have a dev box that's suitable for this project.

perhaps @dbltoe can help us out.  he is one of the users reporting this issue.

**Comment by lat9** [comment]
From the OPC online documentation:
![image](https://user-images.githubusercontent.com/2685585/164982091-4b1afd97-93f4-4edc-9513-67f2618d361b.png)

What 'click' is the square_webPay method attaching to?

**Comment by proseLA** [comment]
https://github.com/proseLA/square_webPay/blob/8c5cad7514139deffd7ebfa8a4eba32fccb0002b/for_upload/includes/modules/pages/checkout_payment/jscript_square_webPay.php#L164-L182

line 166 is where the element gets selected...
line 177 is where the event listener gets added.

the current solution is documented in this post:

https://www.zen-cart.com/showthread.php?228750-Square-WebPay-support-thread&p=1387913#post1387913

i was thinking about in OPC, we could add something like:

```
if (!document.getElementById('card-button') {
  jQuery('form[name="checkout_payment"]').submit();
}
```
in both places...

**Comment by lat9** [comment]
What happens then when a store has multiple payment methods?  Wouldn't that render the submit button processing unusable for payment methods other than square_webPay?

**Comment by proseLA** [comment]
> What happens then when a store has multiple payment methods? Wouldn't that render the submit button processing unusable for payment methods other than square_webPay?

no.  the click button (from square) still submits the form, regardless of the initial return from square.  the first part tokenizes the payment and returns a token.  it then attaches the results of the tokenization to the payment form and then submits the form.  if the method is something other than square, it will not be looking at the attached post vars which will say something of the nature that there was a problem with elements on your submit, so there is no token.  (some nameless people might suggest that what if another enabled payment module makes use of the same names of the post vars.  to which i will respond YAGNI.)  whatever payment method is selected will do its own processing.  that section of the code is here:

https://github.com/proseLA/square_webPay/blob/8c5cad7514139deffd7ebfa8a4eba32fccb0002b/for_upload/includes/modules/pages/checkout_payment/jscript_square_webPay.php#L132-L157

line 157 is where the form gets submitted to ZC. it's doing the exact same thing that we are now commenting out in OPC.

i suppose we could a test to see if the radio select button says `pmt-square_webPay`, but i am currently not doing that with no ill will.

here is one of my local dev sites with multiple payment options in use, including square_webPay, and my authorizenet card on file both enabled.  as you can see the square_webPay elements are inserted, meaning square is active and it is line 157 which is submitting the payment form.

https://www.dropbox.com/s/yp4qud5cq2kaa3r/Screencast%20from%2004-24-2022%2004%3A35%3A00%20PM.webm?dl=0

> 
> **_Update_**: When (and via what processing module) does the 'card-button' element get added to the DOM?

everything for the javascript is here:

https://github.com/proseLA/square_webPay/blob/master/for_upload/includes/modules/pages/checkout_payment/jscript_square_webPay.php

the card element gets added to the DOM here:

https://github.com/proseLA/square_webPay/blob/8c5cad7514139deffd7ebfa8a4eba32fccb0002b/for_upload/includes/modules/pages/checkout_payment/jscript_square_webPay.php#L35-L39

**Comment by lat9** [comment]
> https://github.com/proseLA/square_webPay/blob/8c5cad7514139deffd7ebfa8a4eba32fccb0002b/for_upload/includes/modules/pages/checkout_payment/jscript_square_webPay.php#L164-L182
> 
> line 166 is where the element gets selected... line 177 is where the event listener gets added.
> 
> the current solution is documented in this post:
> 
> https://www.zen-cart.com/showthread.php?228750-Square-WebPay-support-thread&p=1387913#post1387913
> 
> i was thinking about in OPC, we could add something like:
> 
> ```
> if (!document.getElementById('card-button') {
>   jQuery('form[name="checkout_payment"]').submit();
> }
> ```
> 
> in both places...

OK, I'm thinking (to make this change more general) that OPC adds (yet another) configuration setting that identifies the HTML selector(s) associated with any payment-method submit-button override.  For `square_webPay` (and the default), that'll be set to `#card-button`.  Then the code fragment you identified above would be added, but using that configured selector.

**Comment by proseLA** [comment]
hopefully later today.  very busy right now...

**Comment by lat9** [comment]
@dbltoe, could you grab those changes for the square_webPay integration onto your test site to see if that corrects the problem you reported?

**Comment by dbltoe** [comment]
blame it on the trifocals or spring allergies.  I'm not sure what you want me to test.
Do I need to un-comment the OPC  changes from ProseLA and then use the Payment Methods Requiring Confirmation to add the name of the new square?  If so, would it be entered as square_webPay or some other name?

**Comment by lat9** [comment]
@dbltoe, grab the current copy of the `jscript_main.php` and `jquery.checkout_one.js` and `jquery.checkout_one.min.js` from `/includes/modules/pages/checkout_one`.  Those are the main files with the updates to enable (I hope) the integration with `square_webPay`.  No additional configuration changes are needed (or wanted).

**Comment by dbltoe** [comment]
It works!  and with Freeshipper.  Found out earlier that freeshipper was the culprit at spicewoodfood.com
Sorry for the delay.  Been having to contact customers today.
Do I need to add the header.php from that same folder?  I noticed it has changed.

**Comment by dbltoe** [comment]
Don't know if this has anything to do with WebPay but, another site is getting:

[27-Apr-2022 11:52:55 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 193.208.126.18
#1 trigger_error() called at [/includes/classes/OnePageCheckout.php:1410]
#2 OnePageCheckout->inputPreCheck() called at [/includes/classes/OnePageCheckout.php:898]
#3 OnePageCheckout->formatAddress() called at [/includes/classes/observers/class.checkout_one_observer.php:516]
#4 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#5 base->notify() called at [/includes/classes/order.php:1183]
#6 order->send_order_email() called at [/includes/modules/checkout_process.php:103]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Fatal error: Invalid request, tempAddressValues not set. in /includes/classes/OnePageCheckout.php on line 1410.

**Comment by proseLA** [comment]
> Don't know if this has anything to do with WebPay but, another site is getting:
> 
> [27-Apr-2022 11:52:55 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 193.208.126.18 #1 trigger_error() called at [/includes/classes/OnePageCheckout.php:1410] #2 OnePageCheckout->inputPreCheck() called at [/includes/classes/OnePageCheckout.php:898] #3 OnePageCheckout->formatAddress() called at [/includes/classes/observers/class.checkout_one_observer.php:516] #4 checkout_one_observer->update() called at [/includes/classes/class.base.php:118] #5 base->notify() called at [/includes/classes/order.php:1183] #6 order->send_order_email() called at [/includes/modules/checkout_process.php:103] #7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14] #8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35] --> PHP Fatal error: Invalid request, tempAddressValues not set. in /includes/classes/OnePageCheckout.php on line 1410.

i am going to say, no.  nothing to do with webPay.

**Comment by lat9** [comment]
> It works! and with Freeshipper. Found out earlier that freeshipper was the culprit at spicewoodfood.com Sorry for the delay. Been having to contact customers today. Do I need to add the header.php from that same folder? I noticed it has changed.

That `header_php.php` has changes unrelated to the `square_webPay` integration; those changes were associated with the dropping of support for pre-zc157 stores.

**Comment by lat9** [comment]
> Don't know if this has anything to do with WebPay but, another site is getting:
> 
> [27-Apr-2022 11:52:55 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 193.208.126.18 #1 trigger_error() called at [/includes/classes/OnePageCheckout.php:1410] #2 OnePageCheckout->inputPreCheck() called at [/includes/classes/OnePageCheckout.php:898] #3 OnePageCheckout->formatAddress() called at [/includes/classes/observers/class.checkout_one_observer.php:516] #4 checkout_one_observer->update() called at [/includes/classes/class.base.php:118] #5 base->notify() called at [/includes/classes/order.php:1183] #6 order->send_order_email() called at [/includes/modules/checkout_process.php:103] #7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14] #8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35] --> PHP Fatal error: Invalid request, tempAddressValues not set. in /includes/classes/OnePageCheckout.php on line 1410.

Issue opened to track: https://github.com/lat9/one_page_checkout/issues/324
