### ISSUE TITLE
Receiving "Invalid request, tempAddressValues not set." error log

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#324]
Don't know if this has anything to do with WebPay but, another site is getting:

[27-Apr-2022 11:52:55 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 193.208.126.18
#1 trigger_error() called at [/includes/classes/OnePageCheckout.php:1410]
#2 OnePageCheckout->inputPreCheck() called at [/includes/classes/OnePageCheckout.php:898]
#3 OnePageCheckout->formatAddress() called at [/includes/classes/observers/class.checkout_one_observer.php:516]
#4 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#5 base->notify() called at [/includes/classes/order.php:1183]
#6 order->send_order_email() called at [/includes/modules/checkout_process.php:103]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Fatal error: Invalid request, tempAddressValues not set. in /includes/classes/OnePageCheckout.php on line 1410.

_Originally posted by @dbltoe in https://github.com/lat9/one_page_checkout/issues/317#issuecomment-1112670958_

**Comment by dbltoe** [comment]
Just got up from a late night.  I'll not be able to find out for sure till later.  Sorry

**Comment by dbltoe** [comment]
Using 2.3.11 on topkayakerDOTcom

**Comment by lat9** [comment]
v2.4.0 will include additional information in that log to hopefully give some information to aid in locating the source of the issue.

I find it "very interesting" that this happens during the `send_order_email` processing.

**Comment by lat9** [comment]
I believe that this issue was corrected by #355, which modified the way that OPC deals with customers' address formatting.
