### ISSUE TITLE
PHP Warning: var_export does not handle circular references

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#328]
Received on initial entry for a customer's session when OPC debug is enabled:
```
[14-May-2022 14:42:22 Europe/Berlin] Request URI: /zc157posm/index.php?main_page=checkout_one, IP address: 127.0.0.1
#1  var_export() called at [C:\xampp\htdocs\zc157posm\includes\classes\OnePageCheckout.php:567]
#2  OnePageCheckout->startGuestOnePageCheckout() called at [C:\xampp\htdocs\zc157posm\includes\modules\pages\checkout_one\header_php.php:41]
#3  require(C:\xampp\htdocs\zc157posm\includes\modules\pages\checkout_one\header_php.php) called at [C:\xampp\htdocs\zc157posm\index.php:35]
--> PHP Warning: var_export does not handle circular references in C:\xampp\htdocs\zc157posm\includes\classes\OnePageCheckout.php on line 567.
```

**Comment by lat9** [comment]
That last commit (although I've not seen an associated log ... yet) provides a similar change to a similar debug-output.

**Comment by dbltoe** [comment]
Now getting:

[15-May-2022 21:01:46 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 173.45.185.128
#1 var_export() called at [/includes/classes/OnePageCheckout.php:745]
#2 OnePageCheckout->updateOrderAddresses() called at [/includes/classes/observers/class.checkout_one_observer.php:422]
#3 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#4 base->notify() called at [/includes/classes/order.php:425]
#5 order->cart() called at [/includes/classes/order.php:35]
#6 order->__construct() called at [/includes/modules/checkout_process.php:48]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Warning: var_export does not handle circular references in /includes/classes/OnePageCheckout.php on line 745.

[15-May-2022 21:01:46 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 173.45.185.128
#1 var_export() called at [/includes/classes/OnePageCheckout.php:745]
#2 OnePageCheckout->updateOrderAddresses() called at [/includes/classes/observers/class.checkout_one_observer.php:422]
#3 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#4 base->notify() called at [/includes/classes/order.php:425]
#5 order->cart() called at [/includes/classes/order.php:35]
#6 order->__construct() called at [/includes/modules/checkout_process.php:48]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Warning: var_export does not handle circular references in /includes/classes/OnePageCheckout.php on line 745.

[15-May-2022 21:01:46 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 173.45.185.128
#1 var_export() called at [/includes/classes/OnePageCheckout.php:745]
#2 OnePageCheckout->updateOrderAddresses() called at [/includes/classes/observers/class.checkout_one_observer.php:422]
#3 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#4 base->notify() called at [/includes/classes/order.php:425]
#5 order->cart() called at [/includes/classes/order.php:35]
#6 order->__construct() called at [/includes/modules/checkout_process.php:48]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Warning: var_export does not handle circular references in /includes/classes/OnePageCheckout.php on line 745.

[15-May-2022 21:01:46 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 173.45.185.128
#1 var_export() called at [/includes/classes/OnePageCheckout.php:745]
#2 OnePageCheckout->updateOrderAddresses() called at [/includes/classes/observers/class.checkout_one_observer.php:422]
#3 checkout_one_observer->update() called at [/includes/classes/class.base.php:118]
#4 base->notify() called at [/includes/classes/order.php:425]
#5 order->cart() called at [/includes/classes/order.php:35]
#6 order->__construct() called at [/includes/modules/checkout_process.php:48]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Warning: var_export does not handle circular references in /includes/classes/OnePageCheckout.php on line 745.

I will need to get the test site in sync with the main if you want to look at the actual files.  Just let me know.

**Comment by dbltoe** [comment]
test. is  set to mirror the main site for topkayakerDOTcom

**Comment by dbltoe** [comment]
I have now.  Will monitor.

THANX

**Comment by lat9** [comment]
I'll hold off on the v2.4.1 release for a couple of days to see if any more reports 'come in'.

**Comment by njcyx6649250** [comment]
I downloaded the latest OnePageCheckout.php from the github master branch and it worked now. I tested it and no log file is generated. Thanks.

**Comment by lat9** [comment]
Thanks for the come-back, @njcyx6649250!
