### ISSUE TITLE
Guest shipping address 'overwritten' if billing address is changed

### ISSUE THREAD

**Issue by lat9** [lat9/one_page_checkout#332]
As reported in [this](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1388546#post1388546) Zen Cart support-thread posting.

- Using guest checkout, initially enter an address in US/CA.  Shipping quotes (best seen via USPS or UPS methods) are returned for US/CA.
- Untick the "Shipping=Billing" checkbox.  Both billing and shipping addresses show as US/CA.
- Change the billing address to be US/FL and save.  The shipping quotes are now updated to reflect pricing for FL.

**Comment by njcyx6649250** [comment]
Hi @lat9 , I just updated my init_checkout_one.php and OnePageCheckout.php according to your above fix and this bug is fixed on my side! No matter how I changed my billing address, the shipping rate remains unchanged. Thanks!
