### ISSUE TITLE
`languages_id` warning when cart is restored by Keep Cart plugin

### ISSUE THREAD

**Issue by marco-pm** [lat9/one_page_checkout#335]
ZC 1.5.7d
PHP 8.0
OPC 2.4.1, guest checkout enabled
Keep Cart 2.0.2

Not strictly related to the OPC plugin because it happens only if also the Keep Cart plugin is installed.

Add some items to the shopping cart without logging in, then let the session expire (or simply clear the zenid cookie).
Now open the shopping cart page, the shopping cart contents are restored by the Keep Cart plugin.

The following warning is generated:

```
[01-Jun-2022 20:20:23 America/New_York] Request URI: /, IP address: xx.xxx.xxx.xxx
#1  shoppingCart->get_products() called at [/var/www/html/includes/classes/observers/class.checkout_one_observer.php:114]
#2  checkout_one_observer->__construct() called at [/var/www/html/includes/autoload_func.php:44]
#3  require(/var/www/html/includes/autoload_func.php) called at [/var/www/html/includes/application_top.php:222]
#4  require(/var/www/html/includes/application_top.php) called at [/var/www/html/index.php:25]
--> PHP Warning: Undefined array key "languages_id" in /var/www/html/includes/classes/shopping_cart.php on line 1182.
```

From here:

https://github.com/lat9/one_page_checkout/blob/5b9be68290526a65fce4d9c0fdea19fcded21588/includes/classes/observers/class.checkout_one_observer.php#L114

and then on the `get_products()` function shopping cart class: 

```
    foreach($this->contents as $products_id => $data) {
      $products_query = "SELECT p.*, pd.products_name
                           FROM " . TABLE_PRODUCTS . " p, " . TABLE_PRODUCTS_DESCRIPTION . " pd
                           WHERE p.products_id = '" . (int)$products_id . "'
                           AND pd.products_id = p.products_id
                           AND pd.language_id = " . (int)$_SESSION['languages_id'] . " LIMIT 1";
```

the `$_SESSION['languages_id']` is not defined.

I think it's because the `$autoLoadConfig` order for `checkout_one_observer` in `config.checkout_one.php` has been lowered to 97, so not all the session variables have been initialized when the call to `get_products()` is done.

**Comment by lat9** [comment]
Thanks for the detailed report, @marco-pm, I'll move that processing from the observer's constructor to the `messageCheck` method, which is run via auto-loader at CP-131 (after the languages and messageStack have been 'activated').

**Comment by lat9** [comment]
Noting also that the issue has nothing to do with 'Keep Cart'.  With OPC's guest-checkout feature enabled and the customer not logged-in, simply add a "Gift Certificate" product to the cart to see the PHP Warning logged.
