### ISSUE TITLE
Unnecessary definitions in ot_coupon.php and ot_gv.php

### ISSUE THREAD

**Issue by simon1066** [lat9/one_page_checkout#339]
A small thing but although these language defines were removed from the ZC fileset in v1.5.7 they still persist in the OPC repo,

`includes/languages/english/modules/order_total/YOUR_TEMPLATE/ot_coupon.php`

```
define('SHIPPING_NOT_INCLUDED', ' [Shipping not included]');
define('TAX_NOT_INCLUDED', ' [Tax not included]');
define('IMAGE_REDEEM_VOUCHER', 'Redeem Voucher');
```

**Comment by simon1066** [comment]
Sorry I didn't spot this at the time but the above is similarly applicable in 

`includes/languages/english/modules/order_total/YOUR_TEMPLATE/ot_gv.php`

in that 
```
define('SHIPPING_NOT_INCLUDED', ' [Shipping not included]');
define('TAX_NOT_INCLUDED', ' [Tax not included]');
```

were removed from the ZC fileset in v1.5.7 but still persist in the OPC repo.

**Comment by lat9** [comment]
I'll get that captured as well!

**Comment by lat9** [comment]
Now captured!
