### ISSUE TITLE
CSS override folder - is it needed?

### ISSUE THREAD

**Issue by simon1066** [lat9/one_page_checkout#349]
Just wondered whether this override folder `\includes\templates\YOUR_TEMPLATE\css` is needed given the file contents are identical to `\includes\templates\template_default\css`

Isn't it usually up to the user to decide whether or not to create overrides?

**Comment by simon1066** [comment]
Great, thanks for the explanation.

**Comment by lat9** [comment]
No, since `template_default` is the suggested base for any template override.
