### ISSUE TITLE
Note that the Information sidebox changes are already included in the Bootstrap template

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#351]
The docs call for a merge of the Information Sidebox with the site's current template's version of that file (Docs > Installation >1 C 5

I have not been successful with this when the store is using the latest bootstrap cloned to a custom template and using the bootstrap OPC files.

I have found no problem with renaming includes/modules/sideboxes/YOUR_TEMPLATE/information.php to a .jet file prior to upload.

I've not seen any problems or warning logs when I did this.

Just wondering if this is the best solution for the situation.

**Comment by lat9** [comment]
The integration between OPC and the Bootstrap template is covered in https://github.com/lat9/bs4_opc; have you followed the instructions there?

**Comment by dbltoe** [comment]
Followed instructions in both.  BUT, with bootstrap installed, if someone drops the newest OPC, it overwrites the BS4_OPC information file and results in a partial blank screen.
The two files are so adamantly different that even my commercial software is confused on how to merge.

Just looking to see whether just leaving the BS4_OPC is failing to have something vital in the OPC information.php file.

**Comment by lat9** [comment]
Including the log that's generated for that partial whitescreen would help a lot,  I'm not seeing major differences in the information sidebox formatting.

**Comment by lat9** [comment]
I'll be updating the OPC readme for v2.4.4 to indicate that the information sidebox module need not be merged when updating an installation with the Bootstrap template, v3.4.0 or later.
