### ISSUE TITLE
readme.html typo

### ISSUE THREAD

**Issue by simon1066** [lat9/one_page_checkout#352]
Not being a coder I'm afraid all I have left is to focus on the little things - square_wePay != square_we**b**Pay

https://github.com/lat9/one_page_checkout/blob/1b7c6f9838e2b1b869297d5d5969b2ea52d07cc0/docs/one_page_checkout/readme.html#L315-L319

**Comment by lat9** [comment]
"Little" things are important, too!  Thanks, @simon1066.
