### ISSUE TITLE
Possible Cause of Square Token Error

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#358]
per forum thread https://www.zen-cart.com/showthread.php?228750-Square-WebPay-support-thread&p=1391098#post1391098

It's possible for a customer with OPC and WebPay to click on Confirm Order without actually fully entering the data in the WebPay form.  This happens with auto-input of the CC data and is a result of the user not seeing the warning to "! enter the CCV" or "!enter the Zip Code" and seeing an input in the form that has really not been saved.

If the user hits enter or tabs out of the form, no problem.

Is this something addressable by having the Confirm Order disabled until the CC data is filled in or is there a better place to deal with this?

**Comment by lat9** [comment]
If the OPC/square_WebPay integration is properly configured, then the setting _**Payment Methods Handling Form Submittal**_ is set to indicate that `square_WebPay` is one of those payment methods, at which point OPC 'steps out of the way' in the actual form submittal when the currently-selected payment-method is in that comma-separated list.

**Comment by dbltoe** [comment]
thanx for the clarification
