### ISSUE TITLE
When changing country, the zones dropdown is not populated alphabetically

### ISSUE THREAD

**Issue by marco-pm** [lat9/one_page_checkout#359]
When changing country, `updateCountryZones()` (in `jquery.checkout_one_addr.js`) doesn't populate the zones dropdown in alphabetical order; instead, the zones are listed by their IDs.
This is because `c2z` is an object and not an array, `JSON.parse(c2z)` returns an object, therefore the order of the values (zones) is not kept.

Possible solution:
```
jQuery.each(JSON.parse(c2z), function(country_id, country_zones) {
    if (selected_country == country_id) {
        countryHasZones = true;
        var countryZonesArray = [];
        jQuery.each(country_zones, function(zone_id, zone_name) {
            countryZonesArray[zone_name] = zone_id;
        });
        Object.keys(countryZonesArray).sort().forEach(function(zone_name) {
            countryZones += '<option value="' + countryZonesArray[zone_name] + '">' + zone_name + '<' + '/option>';
        });
    }
});
```

basically create a temporary array with the zone names, sort it and then output the zones' id-name pairs. Not very elegant, maybe there's a better solution...

**Comment by lat9** [comment]
Thanks for that, @marco-pm, it works the treat!
