### ISSUE TITLE
Missing language constant "ERROR_GUEST_CHECKOUT_PAGE_DISALLOWED"

### ISSUE THREAD

**Issue by simon1066** [lat9/one_page_checkout#364]
`\includes\languages\english\extra_definitions\lang.checkout_one_extra_definitions.php`

`'ERROR_GUEST_CHECKOUT_PAGE_DISALLOWED', 'Access to that page ....`

should be 

`ERROR_GUEST_CHECKOUT_PAGE_DISALLOWED' => 'Access to that page ....`

as in [this forum post](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1392060#post1392060)

**Comment by dbltoe** [comment]
Line 13 for those interested

**Comment by lat9** [comment]
Thanks, @simon1066, for the update.
