### ISSUE TITLE
`order_status` page results in PHP fatal error on zc157

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#368]
when OPC is installed in v157d using OPC 2.4.4 going to this page:

/index.php?main_page=order_status

results in a fatal error on the following line:

https://github.com/lat9/one_page_checkout/blob/8a0a4cdf55473f894e9d47e336aff3d54f342164/includes/functions/extra_functions/one_page_checkout_functions.php#L140

OPC is looking for a language array file that does not exist.

```
[24-Dec-2022 03:59:47 UTC] PHP Fatal error:  require(): Failed opening required 'includes/languages//english/lang.order_status.php' (include_path='.:/usr/local/php74/pear') in /home/customer/www/mystore/public_html/includes/functions/extra_functions/one_page_checkout_functions.php on line 140
```

**Comment by lat9** [comment]
Those languages files, for the `orders_status` page, are defined in the distribution zip-file's /includes/languages/english/YOUR_TEMPLATE ... since they're core-file overwrites for zc158.

**Comment by proseLA** [comment]
all of the files are in the proper place.

**Comment by proseLA** [comment]
this file is in the WRONG directory:
https://github.com/lat9/one_page_checkout/blob/master/includes/languages/english/YOUR_TEMPLATE/lang.order_status.php

in should not be in the YOUR_TEMPLATE directory as seen here:

https://github.com/lat9/one_page_checkout/blob/a74f5d989754c8193ae5a2e2c3f59b8c64f0141a/includes/languages/english/YOUR_TEMPLATE/order_status.php#L12

no template is passed to the function.

one can either modify the function call to include the template, or move the `lang.order_status.php` to where all of the other said files are.

**Comment by lat9** [comment]
Crud, my zc157 test site has both `order_status` and `lang.order_status` in the base language directory.
