### ISSUE TITLE
"Revisit" session-based variables' handling, do away with `E_USER_ERROR` elements (correcting fatal checkout errors)

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#370]
i have seen this section of code get executed far more than others; on multiple sites.  in almost all examples, it is always because the `$address_book_id` is blank.  at least according to the error message.

https://github.com/lat9/one_page_checkout/blob/e5bedbaccdeb4d99067fdd8146492e0414ac7ade/includes/classes/OnePageCheckout.php#L1086-L1089

it just seems if that var is blank, we can handle the situation perhaps more gracefully.  or at a minimum provide more information in the log, ie `$_SESSION['billto']` and `$_SESSION['sendto']`.  

it would be nice to be able to determine why we are getting here.  

if we wanted to be even better, in theory, we could check the number of address book entries the customer has, and if only one, use that one and move on.

generating a fatal error at a checkout page is one of the least desirable outcomes for any store owner.  i know i get frustrated and then just go purchase elsewhere.

thoughts?

**Comment by lat9** [comment]
Do you, by chance, still have a copy of one of the logs so that I can 'see' what path was taken to the method that triggered the error?

**Comment by lat9** [comment]
I'll start the path, changing that method to also take `which` address book record was being requested so that additional information can be provided in the log.

**Comment by proseLA** [comment]
> Do you, by chance, still have a copy of one of the logs so that I can 'see' what path was taken to the method that triggered the error?

ha ha ha.

no.

i'll be on the lookout for one.

**Comment by lat9** [comment]
I _think_ I might have found the source of the issue.  As the [proverb](https://en.wiktionary.org/wiki/too_many_cooks_spoil_the_broth) states, "Too many cooks spoil the broth".

OPC is keeping **two** session-variables, `$this->guestIsActive` and `$_SESSION['is_guest_checkout']`, that indicate that the current checkout is being processed for a guest-customer.  If those ever get out-of-sync, chaos will rule (and I'm _guessing_ that that's what has been happening)!

I'm in the process of reviewing the overall OPC-class-variable maintenance and will be doing away with the non-class-based flag for follow-on releases.

**Comment by lat9** [comment]
Noting also that the `checkout_one` page's header processing defers letting the base OPC class know that the current order's virtual, which can affect the billing=shipping and other 'sendto' determinations in the base class.
