### ISSUE TITLE
Guest Customer, **do not remove** on Contact Us form

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#371]
Steps to show the situation:

1. place any item in the cart
2. click Continue to Checkout
3. Select Guest Checkout
4. Enter all the information but stop before ordering
5. scroll to the bottom of the page (Contact Us on the footer bar)
6. Click on Contact Us
7. Note that the Full Name: is auto-filled with "Guest Customer, **do not remove**"

The problem, although not terrible, is that the customer literally follows the do not remove and does not enter their Full Name in the form.  And, since the Full Name has an entry, there's no notification to the customer to provide their real name.

Something to stop the insertion in the form if the customer is in the process of Guest Checkout?

**Comment by lat9** [comment]
That 'something' should be in the Zen Cart base; I'm not sure if other guest-checkout contributions are using the `in_guest_checkout` notification ... but they should be.

**Comment by lat9** [comment]
FWIW, I'm not seeing the behavior on zc158.  Going through the steps provided, the Full Name is presented as an empty string.

**Comment by dbltoe** [comment]
You are, of course, correct and I am remiss for not mentioning this was a 1.5.7 problem.

It is not happening in 1.5.8

**Comment by lat9** [comment]
That'll require a *core-file* change to `/includes/modules/pages/contact_us/header_php.php` (line 122 in the zc157 release), changing
```php
if (zen_is_logged_in()) {
```
to
```php
// default email and name if customer is logged in
if (zen_is_logged_in() && !zen_in_guest_checkout()) {
```

**Comment by dbltoe** [comment]
That works perfectly.

Thanx so much for taking the time to address this.  Going outside the box to help is what keeps Zen Cart going.
