### ISSUE TITLE
Different `$_POST['current_order_total']` encoding for space symbol

### ISSUE THREAD

**Issue by marco-pm** [lat9/one_page_checkout#372]
I was investigating a "_Something causing redirection back to checkout_one_" issue on an order and noticed something that has never happened to me before.
The order-total string is "100,00 €" (with a `&nbsp;` space character before the currency symbol)

The value of `$_POST['current_order_total']` used here:
```
$session_start_hash = $checkout_one->hashSession(!empty($_POST['current_order_total']) ? $_POST['current_order_total'] : 0);
```

was different from the value of `$order->info['total']` used here:
```
$session_end_hash = $checkout_one->hashSession($currencies->format($order->info['total']));`
```

Specifically, the space character `&nbsp;` in the order total value was handled differently.
In `$_POST['current_order_total']` the space was saved as ASCII 32 (0x20 HEX).
In `$order->info['total']` the space was saved as ASCII 160 (0xa0 HEX).

So far, the space in `$_POST['current_order_total']` had always been saved as ASCII 160. But not this time. 

I know that the `checkout_one_observer` class does some "cleaning":
```
$current_order_total = str_replace(["\n", "\r"], '', $current_order_total);
$session_data['order_current_total'] = html_entity_decode($current_order_total, ENT_COMPAT, CHARSET);
```

but it doesn't affect the value in this case.
The spaces in the two values are two different ASCII symbols, therefore `$session_start_hash` will always be different from `$session_end_hash`.

 `$_POST['current_order_total']` comes from this jQuery code:

https://github.com/lat9/one_page_checkout/blob/e5bedbaccdeb4d99067fdd8146492e0414ac7ade/includes/modules/pages/checkout_one/jquery.checkout_one.js#L286-L288

so it seems that somehow this time JS or jQuery handled the output of the order-total value in in a slightly different way.
Don't know why... maybe some different Javscript/browser encoding behavior?
But apparently you can't trust that `$_POST['current_order_total']` value 100%, at least for symbols. So in my case I'm adding some additional "scrubbing" to remove spaces and special characters in `$session_data['order_current_total']`.

**Comment by lat9** [comment]
Thanks for the report and, as always, the detailed analysis.

**Comment by lat9** [comment]
FWIW, I found [this](https://www.codetable.net/hex/a0) article that identifies what 0xA0 means.  It looks like it's a `latin1` encoding; does the site in question use such an encoding in its main language file(s)?

**Comment by lat9** [comment]
Nope, that `&nbsp;` is specifically called out in PHP's documentation of [html_entity_decode](https://www.php.net/manual/en/function.html-entity-decode).

**Comment by marco-pm** [comment]
The charset is UTF-8.
If I do `html_entity_decode('&nbsp;', 2, 'UTF-8')` I get `0xA0` (with square brackets at the start and end), which is indeed the UTF-8 encoding of a non-breaking space.

In a "normal" situation, if the order-total is, e.g., 9 euro:

`$_POST['current_order_total']` = '90xA0&euro;' (already in UTF-8)
`$session_data['order_current_total']` (after `html_entity_decode') = '90xA0&euro;' (no change, because it was already in UTF-8)

`$order->info['total']` = '9&nbsp;&euro;' (ASCII string)
`$session_data['order_current_total']` (after `html_entity_decode') = '90xA0&euro;' (converted to UTF-8).

In the above case instead, the issue was that

`$_POST['current_order_total']` = '90x20&euro;'`

I.e., despite the checkout page having a UTF-8 character set, the non-breaking space of the order-total was written as a normal ASCII space, and then transmitted as POST variable in that format. As if the charset had been overridden by the browser or similar.

**Comment by lat9** [comment]
Thanks for the additional details @marco-pm; that'll help to find the _right_ solution to the issue!

**Comment by lat9** [comment]
@marco-pm, I'm pretty sure that the change just submitted will correct the issue you described, essentially removing *all* whitespace characters from the order's total value submitted.  Let me know if you do/don't agree!

**Comment by marco-pm** [comment]
> @marco-pm, I'm pretty sure that the change just submitted will correct the issue you described, essentially removing _all_ whitespace characters from the order's total value submitted. Let me know if you do/don't agree!

Seems good to me!

Thank you as usual.
