### ISSUE TITLE
Downloadable Products (with attribute) asking for Shipping

### ISSUE THREAD

**Issue by JeffMash** [lat9/one_page_checkout#384]
Running ZC 1.5.8a with Bootstrap template and OPC 2.4.6

**Issue**: When you go to purchase a download product by itself, trying to apply a coupon or trying to checkout in any fashion will throw this error:

_"Either the available shipping options or your chosen shipping method's price has changed. Please re-select/review your desired shipping method."_

**Product Info Settings:**

- Product is Virtual: No, Shipping Address Required
- Always Free Shipping: No, Normal Shipping Rules

**Attribute Settings:**

- Used For Display Purposes Only: No
- Attribute is Free When Product is Free: Yes
- Default Attribute, Pre-Selected: No
- Apply Discounts Used by Product Special/Sale: Yes
- Include in Base Price When Priced by Attributes: Yes
- Attribute Required for Text or File: No
-  Filename:  NameOfFile.mp4
- Expiry days: 0
- Maximum download count: 50

**Attached is a debug file**

[one_page_checkout-27905-2023-08-31.log](https://github.com/lat9/one_page_checkout/files/12491649/one_page_checkout-27905-2023-08-31.log)

**Comment by lat9** [comment]
No updates, I've been crazy busy but should have some slack in a week or so.

**Comment by JeffMash** [comment]
This is still a very big issue, and I'm hoping you can confirm if this is a bug or just a misconfiguration in our store.

Again, the issue is if we try to create a virtual product (meaning a product that gives access to a downloadable file), the user CANNOT check out.  They get the following error when they try to review or confirm the order:

"Either the available shipping options or your chosen shipping method's price has changed. Please re-select/review your desired shipping method."

The settings for the product are currently these (although I've tried a bunch of different combinations):

Product is Virtual: Yes, Skip Shipping Address (I've tried with NO as well, same result)
Always Free Shipping: No, Normal Shipping Rules (I've tried with YES as well, same result)

Without this addressed (identified as a bug or working but a possible misconfiguration on my part), I am not able to offer ANY sort of virtual/downloads to our customers.

**Comment by JeffMash** [comment]
What part of the code handles this error check during checkout?  What I'd like to do is take the file I have and compare it to the released version (to isolate any changes that may have been made on our end).  I suspect that may be the cause but I need help in finding where to look.

**Comment by lat9** [comment]
Do you have the `freeshipper` shipping module enabled?  That's needed for orders that have free shipping, like those with only 'virtual' products.

**Comment by JeffMash** [comment]
Yes, I do.  Here are my freeshipper settings:

```
Enable Free Shipping
True

Free Shipping Cost
0.00

Handling Fee
0

Tax Class
--none--

Shipping Zone
--none--

Sort Order
0
```

But I am wondering if something may have been edited on my end to tweak the way it behaves.   If you can tell me what file(s) to look at (on my system) to compare with the released versions (with OPC), I can use WinDiff to maybe see if it's something I did in the code which is causing this.

**Comment by lat9** [comment]
That message (ERROR_PLEASE_RESELECT_SHIPPING_METHOD) comes out of either
1. /includes/classes/ajax/zcAjaxOnePageCheckout.php
2. /includes/modules/pages/checkout_one/header_php.php

**Comment by JeffMash** [comment]
> That message (ERROR_PLEASE_RESELECT_SHIPPING_METHOD) comes out of either
> 
>     1. /includes/classes/ajax/zcAjaxOnePageCheckout.php
> 
>     2. /includes/modules/pages/checkout_one/header_php.php

Thanks for pointing me in a direction.  My ajax file is identical.

However, I noticed that my header_php is version 2.4.4 even though my version under Admin -> OPC Settings says it's 2.4.6..   So maybe I had a file not get merged correctly.

For the heck of it, I just uploaded the entire header_php.php file onto my server to see what would happen, but it immediately generated a hard error:

`PHP Fatal error:  Cannot declare class order, because the name is already in use in /home/mydomain/public_html/store/includes/classes/order.php `

So it looks like I may have more to look at than simply replacing a file.

**Comment by lat9** [comment]
Just because a module's "Last updated" comment doesn't reflect the installed version doesn't mean that the file's not correct; those comments are only updated when the file's been updated for a specific version.  _However_, in this case, it's a **red-flag** since that file was updated for v2.4.6 and it's as-distributed comments reflect that.

I'd be looking for storefront files that include `order.php` since that's going to be associated with a non-standard file loading the order.php class.

**Comment by JeffMash** [comment]
Thanks Cindy.......that must have been it (an overlooked file on our side, which is honestly what I was thinking all along).   I just needed an extra brain to help me pinpoint things!
