### ISSUE TITLE
Canadian State shows in the Shipping Estimator but not a Checkout

### ISSUE THREAD

**Issue by dbltoe** [lat9/one_page_checkout#385]
Possibly an OCB customer but, if there's one or two that complain....

Entering a Canadian address works fine and the display is usually correct except on the checkout page where the state is not displayed unless you click edit.

It does not show in the user's My Personal Address Book either but that's outside OPC.

It shows up with shipstation and on the packing slip.

one customer refused to place an order as she knew it would get lost.

"Just because you're paranoid, doesn't mean everyone's not out to get you."

**Comment by lat9** [comment]
Always displaying states as pulldowns?  What version of Zen Cart and OPC?

Noting that if the state doesn't show in the customer's address-book, while that's "outside of OPC" it's certainly indicative of a root cause also outside of OPC.

**Comment by lat9** [comment]
Closing due to lack of response.
