### ISSUE TITLE
v157; An invalid form control with name='state[bill]' is not focusable.

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#393]
i have 2 dev sites with the same code base, and what looks to be the same database, and the error is only coming up on 1 of the sites; but it is a client side error, and i am using the same browser to get at both sites.

this error is effectively talked about [here.](https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable)

on the checkout page, i am in the following div:
```
<div id="address-form-bill" class="hiddenField">
```
and i believe that class should hide all of the inputs.

within that div, we have the following element:
```
<input class="form-control" type="text" name="state[bill]" size = "33" maxlength = "32" id="state-bill" placeholder="*"  required />
```

now the state is always displayed as a pulldown.  so this id should not be required.  which looks to be accomplished by changing the config value of `ENTRY_STATE_MIN_LENGTH` to 0.

but the interesting thing as i previously stated is that it only happens on 1 dev site; and not the other.  and both have that config value set to 2.

thoughts?

here is the console log errors:

![image](https://github.com/lat9/one_page_checkout/assets/1095136/f970f665-55e2-4a80-94c3-0a476e0762f9)

**Comment by lat9** [comment]
Sounds very similar to #381 (not visible vs. not focusable).  What version of OPC is in use?

**Comment by proseLA** [comment]
yes that was the problem...

the version was a few back.  

thanks for the help on that.
