### ISSUE TITLE
Change to consider for credit_selection

### ISSUE THREAD

**Issue by scottcwilson** [lat9/one_page_checkout#397]
A credit_selection may or may not have a 'field' setting or a 'checkbox' setting.  So in `includes/templates/bootstrap/templates/tpl_modules_opc_credit_selections.php` I changed the `foreach` loop from 

```
            <label class="inputLabel"<?php echo (!empty($current_field['tag'])) ? (' for="' . $current_field['tag'] . '"') : ''; ?>><?php echo $current_field['title']; ?></label><?php echo $current_field['field']; ?>
            <div class="mt-3 text-right"><?php echo zen_image_button(BUTTON_IMAGE_SUBMIT, ALT_TEXT_APPLY_DEDUCTION, $additional_parms, $secondary_class); ?></div>
```

to 

```<?php if (!empty($current_field['field'])) { ?>
            <label class="inputLabel"<?php echo (!empty($current_field['tag'])) ? (' for="' . $current_field['tag'] . '"') : ''; ?>><?php echo $current_field['title']; ?></label><?php echo $current_field['field']; ?>
<?php if (!empty($current_selection['checkbox']) || !empty($current_field['field'])) { ?>
            <div class="mt-3 text-right"><?php echo zen_image_button(BUTTON_IMAGE_SUBMIT, ALT_TEXT_APPLY_DEDUCTION, $additional_parms, $secondary_class); ?></div>
<?php } ?>
```

So now you can have:
<img width="200" alt="credit" src="https://github.com/lat9/one_page_checkout/assets/4391638/37bb43a9-de0b-4cf8-9a01-e00f2800d955">

a credit selection with no apply because there's nothing to apply yet.

**Comment by lat9** [comment]
This, too, needs to be reflected as a change in the Bootstrap template's repo (https://github.com/lat9/ZCA-Bootstrap-Template), since the 'base' OPC templates are distributed in the `template_default` sub-directory.

**Comment by lat9** [comment]
Where did that stray `<?php } ?>` after the `<label>` tag come from?

**Comment by scottcwilson** [comment]
Finger trouble.
