### ISSUE TITLE
Suggestion: retain shipping method legend even if no shipping available 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/one_page_checkout#406]
Otherwise the message is just sort of hanging out with no context. 

<img width="500" alt="no_ship" src="https://github.com/lat9/one_page_checkout/assets/4391638/1a64b045-823c-4332-82bd-4ee741d842ab">

Change is just adding 

`    <legend><?php echo TABLE_HEADING_SHIPPING_METHOD; ?></legend>`
directly above 
`    <h2 id="checkoutShippingHeadingMethod"><?php echo TITLE_NO_SHIPPING_AVAILABLE; ?></h2>`

in `includes/templates/template_default/templates/tpl_modules_opc_shipping_choices.php`.

**Comment by lat9** [comment]
Noting, mostly as a reminder-to-self, that any change in that base OPC template warrants a similar change in the Bootstrap template's version.

**Comment by lat9** [comment]
Is it valid HTML to have a `<legend>` tag without an associated `<fieldset>`?

**Comment by drbyte** [comment]
> Is it valid HTML to have a `<legend>` tag without an associated `<fieldset>`?

Doesn't seem to be. Seems like legend is a child of fieldset.
https://www.w3schools.com/TAGS/tag_legend.asp

**Comment by lat9** [comment]
> > Is it valid HTML to have a `<legend>` tag without an associated `<fieldset>`?
> 
> Doesn't seem to be. Seems like legend is a child of fieldset. https://www.w3schools.com/TAGS/tag_legend.asp

Thanks, that was my "read" as well.
