### ISSUE TITLE
"Simplify" further the reason to kick-back from confirmation to order-entry

### ISSUE THREAD

**Issue by proseLA** [lat9/one_page_checkout#414]
i am getting the dreaded: **"Your order's details have changed. Please review the current values and re-submit."** when nothing on the order has changed.

rather than send a log, i decided to do a bit of debugging myself.  which proved tricky, as my debugger would show a different value than what the log would show for the `$order->info['total']`.  here is the order:

![image](https://github.com/lat9/one_page_checkout/assets/1095136/f9d2fa5a-aa64-44f1-83d7-49b2583a2165)

i have resolved the issue by providing a new function:

```php
function setFloatPrecision(array $input): array
    {
        $precision = 13;
        foreach ($input as $key => $value) {
            if (is_float($value)) {
                $value = round($value, $precision);
            }
            $output[$key] = $value;
        }
        return $output;
    }
```
i then modified the following 2 lines to pass the `$order->info` to the function, prior to the `json_encode`.
https://github.com/lat9/one_page_checkout/blob/21f492fd4838e5dd64ea8aba47f2376db38cad7b/includes/modules/pages/checkout_one/header_php.php#L355

https://github.com/lat9/one_page_checkout/blob/21f492fd4838e5dd64ea8aba47f2376db38cad7b/includes/modules/pages/checkout_one_confirmation/header_php.php#L196

for the example above, at a precision of 13, the order passed validation; at 14 the hashes did not match.

needless to say, the precision number can be another one of these soft config values of which i am a fan.

while this may be a hack, i would argue that all of the order total modules are a bit of a hack.  i think the effort put it by @piloujp in the order total modules only proves my point.

**Comment by lat9** [comment]
A copy of the log would help me do some debug as well.  Direct email is just fine.
