### ISSUE TITLE
tpl_ajax_checkout_confirmation

### ISSUE THREAD

**Issue by drbyte** [lat9/one_page_checkout#47]
NOTE: The `tpl_ajax_checkout_confirmation_default.php` is supposed to be a near mimic of `tpl_checkout_confirmation_default.php` save for specific differences for the ajax calls. 

I'm not sure if the "all" differences for this file in this mod are intended, or just missing some merges?

**Comment by lat9** [comment]
Thanks, DrByte.  I'll review and update back.

**Comment by lat9** [comment]
The difference (1 marked code-block) between the plugin's version and that present in the ZC1.5.5a responsive_classic template incorporates a change necessary for some client shipping customizations that don't "interfere" with _normal_ operation.
